### ISSUE TITLE
table of content displayed incorrect

### ISSUE THREAD

**Issue by Qballjos** [TryGhost/Dope#16]
Hi,

first of damn realy nice theme!!

I have a small issue when using:
https://ghost.org/docs/tutorials/adding-a-table-of-contents/

you can view the result here:
https://josvisserict.nl/ambilight-met-raspberry-pi-en-philips-hue/

as you can see on the left side of the table of content it's missing the bar and alignement is incorrect.
is it possible to hard code this feature in the theme so people only have to use the html tag to enable it or just fix the view issues?

**Comment by minimaluminium** [comment]
Hey @Qballjos,

I was able to make the list like below (screenshot on the bottom) with some minor CSS changes. Every theme has some unique styling, and there will most likely be some minor updates/adjustments depending on themes.

```css
.toc-list {
    padding-left: 0;
}

.toc-list .toc-list {
    padding-left: 10px;
}

a.toc-link {
    padding-left: 10px;
}

.toc-link::before {
    margin-top: 3px;
}

.toc-link::after {
    display: none;
}
```

We ask that you please do not use GitHub for support or feature requests 😄. We use GitHub solely for bug-tracking and on-going feature development.

Our [forum](https://forum.ghost.org/) is a great place to get community support, plus it helps create a central location for searching problems/solutions.

### The list after the fix:

![Screen Shot 2021-03-12 at 3 07 06 PM](https://user-images.githubusercontent.com/1418797/110905129-f8caff00-8344-11eb-9b83-51e23726519a.png)
